name: 🐳 Publish Docker Image

on: [push]
env:
    BRIDGE_RUNNER_TOKEN: ${{ secrets.BRIDGE_RUNNER_TOKEN }}

jobs:
  publish-encrypted-bridge-docker-image:
    runs-on: ubuntu-latest  
    steps:
      - uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build the Bridge Docker image
        run: |
          docker build . --tag ghcr.io/cj42/hackathon-ethdam-2025:latest
          docker run ghcr.io/cj42/hackathon-ethdam-2025:latest
          docker push ghcr.io/cj42/hackathon-ethdam-2025:latest